//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biz.dfch.CS.Appclusive.UI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("biz.dfch.CS.Appclusive.UI.App_LocalResources.GeneralResources", typeof(GeneralResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACE.
        /// </summary>
        public static string Ace {
            get {
                return ResourceManager.GetString("Ace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACEs.
        /// </summary>
        public static string Aces {
            get {
                return ResourceManager.GetString("Aces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACL.
        /// </summary>
        public static string Acl {
            get {
                return ResourceManager.GetString("Acl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACLs.
        /// </summary>
        public static string Acls {
            get {
                return ResourceManager.GetString("Acls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        public static string Approval {
            get {
                return ResourceManager.GetString("Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assoc.
        /// </summary>
        public static string Assoc {
            get {
                return ResourceManager.GetString("Assoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit trail.
        /// </summary>
        public static string AuditTrail {
            get {
                return ResourceManager.GetString("AuditTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string Back2list {
            get {
                return ResourceManager.GetString("Back2list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Cart.
        /// </summary>
        public static string BackToCart {
            get {
                return ResourceManager.GetString("BackToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to catalogue.
        /// </summary>
        public static string BackToCatalogue {
            get {
                return ResourceManager.GetString("BackToCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to order.
        /// </summary>
        public static string BackToOrder {
            get {
                return ResourceManager.GetString("BackToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelLink {
            get {
                return ResourceManager.GetString("CancelLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart item.
        /// </summary>
        public static string CartItem {
            get {
                return ResourceManager.GetString("CartItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue.
        /// </summary>
        public static string Catalogue {
            get {
                return ResourceManager.GetString("Catalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue item.
        /// </summary>
        public static string CatalogueItem {
            get {
                return ResourceManager.GetString("CatalogueItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue items.
        /// </summary>
        public static string CatalogueItems {
            get {
                return ResourceManager.GetString("CatalogueItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string CatalogueStatusEnum_Hidden {
            get {
                return ResourceManager.GetString("CatalogueStatusEnum_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string CatalogueStatusEnum_Published {
            get {
                return ResourceManager.GetString("CatalogueStatusEnum_Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoked.
        /// </summary>
        public static string CatalogueStatusEnum_Revoked {
            get {
                return ResourceManager.GetString("CatalogueStatusEnum_Revoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out cart.
        /// </summary>
        public static string CheckOutCart {
            get {
                return ResourceManager.GetString("CheckOutCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cimi target.
        /// </summary>
        public static string CimiTarget {
            get {
                return ResourceManager.GetString("CimiTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to checkout?.
        /// </summary>
        public static string ConfirmCheckOut {
            get {
                return ResourceManager.GetString("ConfirmCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract mapping.
        /// </summary>
        public static string ContractMapping {
            get {
                return ResourceManager.GetString("ContractMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract mappings.
        /// </summary>
        public static string ContractMappings {
            get {
                return ResourceManager.GetString("ContractMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost centre.
        /// </summary>
        public static string CostCentre {
            get {
                return ResourceManager.GetString("CostCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailsLink {
            get {
                return ResourceManager.GetString("DetailsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditLink {
            get {
                return ResourceManager.GetString("EditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of life.
        /// </summary>
        public static string EndOfLife {
            get {
                return ResourceManager.GetString("EndOfLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint.
        /// </summary>
        public static string Endpoint {
            get {
                return ResourceManager.GetString("Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity kind.
        /// </summary>
        public static string EntityKind {
            get {
                return ResourceManager.GetString("EntityKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity type.
        /// </summary>
        public static string EntityType {
            get {
                return ResourceManager.GetString("EntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires at.
        /// </summary>
        public static string ExpiresAt {
            get {
                return ResourceManager.GetString("ExpiresAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gate.
        /// </summary>
        public static string Gate {
            get {
                return ResourceManager.GetString("Gate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be unique and the full name of a core type..
        /// </summary>
        public static string GateHelpText {
            get {
                return ResourceManager.GetString("GateHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string GateStatusEnum_Free {
            get {
                return ResourceManager.GetString("GateStatusEnum_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string GateStatusEnum_Locked {
            get {
                return ResourceManager.GetString("GateStatusEnum_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrier.
        /// </summary>
        public static string GateTypeEnum_Barrier {
            get {
                return ResourceManager.GetString("GateTypeEnum_Barrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string GateTypeEnum_Default {
            get {
                return ResourceManager.GetString("GateTypeEnum_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutex.
        /// </summary>
        public static string GateTypeEnum_Mutex {
            get {
                return ResourceManager.GetString("GateTypeEnum_Mutex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semaphore.
        /// </summary>
        public static string GateTypeEnum_Semaphore {
            get {
                return ResourceManager.GetString("GateTypeEnum_Semaphore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpinLock.
        /// </summary>
        public static string GateTypeEnum_SpinLock {
            get {
                return ResourceManager.GetString("GateTypeEnum_SpinLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to ACL.
        /// </summary>
        public static string GoToAcl {
            get {
                return ResourceManager.GetString("GoToAcl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to carts.
        /// </summary>
        public static string GoToCarts {
            get {
                return ResourceManager.GetString("GoToCarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to product.
        /// </summary>
        public static string GoToProduct {
            get {
                return ResourceManager.GetString("GoToProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Text.
        /// </summary>
        public static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request will be approved when you click the &apos;Approve&apos; button. You can optionally add a explanation or reason for approval..
        /// </summary>
        public static string HelpTextApprove {
            get {
                return ResourceManager.GetString("HelpTextApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This table shows all modifications to the underlying entities.
        /// </summary>
        public static string HelpTextAuditTrail {
            get {
                return ResourceManager.GetString("HelpTextAuditTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request will be declined when you click the &apos;Decline&apos; button. You can optionally add a explanation or reason for approval..
        /// </summary>
        public static string HelpTextDecline {
            get {
                return ResourceManager.GetString("HelpTextDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart item of cart.
        /// </summary>
        public static string ItemOfCart {
            get {
                return ResourceManager.GetString("ItemOfCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog item of catalog.
        /// </summary>
        public static string ItemOfCatalog {
            get {
                return ResourceManager.GetString("ItemOfCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order item of order.
        /// </summary>
        public static string ItemOfOrder {
            get {
                return ResourceManager.GetString("ItemOfOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string JobStatusEnum_Canceled {
            get {
                return ResourceManager.GetString("JobStatusEnum_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string JobStatusEnum_Completed {
            get {
                return ResourceManager.GetString("JobStatusEnum_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string JobStatusEnum_Created {
            get {
                return ResourceManager.GetString("JobStatusEnum_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faulted.
        /// </summary>
        public static string JobStatusEnum_Faulted {
            get {
                return ResourceManager.GetString("JobStatusEnum_Faulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string JobStatusEnum_Running {
            get {
                return ResourceManager.GetString("JobStatusEnum_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitingForActivation.
        /// </summary>
        public static string JobStatusEnum_WaitingForActivation {
            get {
                return ResourceManager.GetString("JobStatusEnum_WaitingForActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitingForChildrenToComplete.
        /// </summary>
        public static string JobStatusEnum_WaitingForChildrenToComplete {
            get {
                return ResourceManager.GetString("JobStatusEnum_WaitingForChildrenToComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitingToRun.
        /// </summary>
        public static string JobStatusEnum_WaitingToRun {
            get {
                return ResourceManager.GetString("JobStatusEnum_WaitingToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration (KNV).
        /// </summary>
        public static string KeyNameValue {
            get {
                return ResourceManager.GetString("KeyNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  list.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management credential.
        /// </summary>
        public static string ManagementCredential {
            get {
                return ResourceManager.GetString("ManagementCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naming convention: use project namespace as prefix.
        /// </summary>
        public static string ManagementCredentialNameInfo {
            get {
                return ResourceManager.GetString("ManagementCredentialNameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management uri.
        /// </summary>
        public static string ManagementUri {
            get {
                return ResourceManager.GetString("ManagementUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management uris.
        /// </summary>
        public static string ManagementUris {
            get {
                return ResourceManager.GetString("ManagementUris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified by.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node (Inventory).
        /// </summary>
        public static string Node {
            get {
                return ResourceManager.GetString("Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not before.
        /// </summary>
        public static string NotBefore {
            get {
                return ResourceManager.GetString("NotBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear audit log.
        /// </summary>
        public static string OperationClearAuditLog {
            get {
                return ResourceManager.GetString("OperationClearAuditLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise update configuration event.
        /// </summary>
        public static string OperationRaiseUpdateConfigurationEvent {
            get {
                return ResourceManager.GetString("OperationRaiseUpdateConfigurationEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload products.
        /// </summary>
        public static string OperationReloadProducts {
            get {
                return ResourceManager.GetString("OperationReloadProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set created by.
        /// </summary>
        public static string OperationSetCreatedBy {
            get {
                return ResourceManager.GetString("OperationSetCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Entity Type&apos; must include full namespace (biz.dfch.CS.Appclusive.Core.OdataServices.Core.Ace).
        /// </summary>
        public static string OperationSetCreatedByHelpText {
            get {
                return ResourceManager.GetString("OperationSetCreatedByHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set tenant.
        /// </summary>
        public static string OperationSetTenant {
            get {
                return ResourceManager.GetString("OperationSetTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Entity Type&apos; must include full namespace (biz.dfch.CS.Appclusive.Core.OdataServices.Core.Ace).
        /// </summary>
        public static string OperationSetTenantHelpText {
            get {
                return ResourceManager.GetString("OperationSetTenantHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id.
        /// </summary>
        public static string OrderId {
            get {
                return ResourceManager.GetString("OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order item.
        /// </summary>
        public static string OrderItem {
            get {
                return ResourceManager.GetString("OrderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent id.
        /// </summary>
        public static string ParentId {
            get {
                return ResourceManager.GetString("ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref Id.
        /// </summary>
        public static string ReferencedItemId {
            get {
                return ResourceManager.GetString("ReferencedItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server role.
        /// </summary>
        public static string ServerRole {
            get {
                return ResourceManager.GetString("ServerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special operations.
        /// </summary>
        public static string SpecialOperations {
            get {
                return ResourceManager.GetString("SpecialOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string Tenant {
            get {
                return ResourceManager.GetString("Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Id.
        /// </summary>
        public static string TenantId {
            get {
                return ResourceManager.GetString("TenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenants.
        /// </summary>
        public static string Tenants {
            get {
                return ResourceManager.GetString("Tenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid from.
        /// </summary>
        public static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid until.
        /// </summary>
        public static string ValidUntil {
            get {
                return ResourceManager.GetString("ValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid VDI.
        /// </summary>
        public static string VDI_INVALID_HelpText {
            get {
                return ResourceManager.GetString("VDI_INVALID_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add personal VDI.
        /// </summary>
        public static string VDI_PERSONAL {
            get {
                return ResourceManager.GetString("VDI_PERSONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add technical VDI.
        /// </summary>
        public static string VDI_PERSONAL_HelpText {
            get {
                return ResourceManager.GetString("VDI_PERSONAL_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add VDI for technical use.
        /// </summary>
        public static string VDI_TECHNICAL {
            get {
                return ResourceManager.GetString("VDI_TECHNICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are requestiong a VDI for antoher user.
        /// </summary>
        public static string VDI_TECHNICAL_HelpText {
            get {
                return ResourceManager.GetString("VDI_TECHNICAL_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VDI.
        /// </summary>
        public static string VdiCartItem {
            get {
                return ResourceManager.GetString("VdiCartItem", resourceCulture);
            }
        }
    }
}
